apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
  namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /etc/loki
