apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/grafana
