apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: observability
  labels:
    app: promtail
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: observability
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/component: logs
    app.kubernetes.io/version: "2.9.8"
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
        app.kubernetes.io/name: promtail
        app.kubernetes.io/instance: observability
        app.kubernetes.io/part-of: observability
        app.kubernetes.io/component: logs
        app.kubernetes.io/version: "2.9.8"
    spec:
      containers:
        - name: promtail
          image: grafana/promtail:2.9.8
          imagePullPolicy: IfNotPresent
          args:
            - -config.file=/etc/promtail/promtail.yaml
          ports:
            - name: http
              containerPort: 9080
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 65534
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: varlog
              mountPath: /var/log
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: varlog
          hostPath:
            path: /var/log
